databases:
  - name: nexusExam
    plan: free
    databaseName: nexusExam
    user: nexusExam

services:
  - type: web
    name: nexusExam
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nexusExam
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
